const express = require('express');
const upload = require('../middleware/payment');
const OrderController = require('../controllers/ordersController');
const authenticateToken = require('../middleware/auth');
const router = express.Router();
router.post('/', upload.single('payment_screen_short'), OrderController.createOrder);
router.get('/', authenticateToken, OrderController.getAllOrders);
router.get('/:id', authenticateToken, OrderController.getOrderById);
router.put('/:id', authenticateToken, upload.single('payment_screen_short'), OrderController.updateOrder);
router.delete('/:id', authenticateToken, OrderController.deleteOrder);
router.patch('/:id/complete', authenticateToken, OrderController.completeOrder);
module.exports = router;